# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04bb66f597e760c0cb3ec6d0c1909fd7fd6e3862aadab7ed9e3fd1983966794df9935f46040a60ba6343836788c8870f7576d75781611488bbebb64971cd2df6

test:
  secret_key_base: 56006007abab85891f7b9cacec3f6003012cb3d1a8c1b05ec9f0d9024502bff61542a4120681f78be505a2ebeeddb36f1b11b3edf7e87deec802f0ab7e16edce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
